Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,6 +42,9 @@ jobs:
         run: |
           pytest --cov=src --cov-report=xml --cov-report=term
 
+      - name: Check if coverage report exists
+        run: ls -l coverage.xml || echo "coverage.xml not found"
+
       - name: Patch project version
         run: |
           if [ -f sonar/version.py ]; then
